default_config:
cloud:

input_button: !include helpers/input_button.yaml
input_boolean: !include helpers/input_boolean.yaml
input_number: !include helpers/input_number.yaml
input_datetime: !include helpers/input_datetime*.yaml
input_select: !include helpers/input_select*.yaml

binary_sensor: !include devices/binary_sensor.yaml

automation: !include config/automations.yaml
person: !include config/people.yaml
tts: !include config/text_to_speech.yaml
http: !include config/http.yaml
google_assistant: !include config/google_assistant.yaml


