default_config:
cloud:
custom_event:
  
input_button: !include helpers/input_button.yaml

input_number: !include_dir_merge_named helpers/input_number/
input_boolean: !include_dir_merge_named helpers/input_boolean/
input_datetime: !include_dir_merge_named helpers/input_datetime/
input_select: !include_dir_merge_named helpers/input_select/

binary_sensor: !include devices/binary_sensor.yaml

automation manual: !include_dir_merge_list config/automations/
automation ui: !include automations.yaml
person: !include config/people.yaml
tts: !include config/text_to_speech.yaml
http: !include config/http.yaml
google_assistant: !include config/google_assistant.yaml
zha: !include config/zigbee_home_assistant.yaml

template: !include_dir_merge_list devices/templates/

homeassistant: !include_dir_named config/homeassistant/
frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: storage
  dashboards:
    mobile-dashboard:
      mode: yaml
      title: Marsh Court
      icon: mdi:home
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/mobile/index.yaml

sensor:
  - platform: mqtt_room
    device_id: "iBeacon:0b466121-31c0-4eb0-bd36-3bcb62fa52c4-100-1"
    name: 'Galaxy S23 BLE Beacon'
    state_topic: 'espresense/devices/iBeacon:0b466121-31c0-4eb0-bd36-3bcb62fa52c4-100-1'
    timeout: 10
    away_timeout: 120
  