# Loads default set of integrations. Do not remove.
default_config:

cloud:

input_button: !include helpers/input_button.yaml
input_boolean: !include helpers/input_boolean.yaml
input_number: !include helpers/input_number.yaml
input_datetime: !include helpers/input_datetime.yaml
input_select: !include helpers/input_select.yaml

      
# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

binary_sensor: !include devices/binary_sensor.yaml
