# Loads default set of integrations. Do not remove.
default_config:

cloud:

input_button: !include helpers/input_button.yaml
input_boolean: !include helpers/input_boolean.yaml
input_number: !include helpers/input_number.yaml
input_datetime: !include helpers/input_datetime.yaml
input_select: !include helpers/input_select.yaml

      
# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

binary_sensor: !include devices/binary_sensor.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

google_assistant:
  project_id: home-assistant-24120
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true
