version: 2.1

jobs:
  verify:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: "Tests"
          command: "pytest"
      - run:
          name: "Mypy"
          command: "mypy apps"

workflows:
  validate-config:
    jobs:
      - test
