---
- platform: group
  name: kitchen_motion
  device_class: motion
  entities:
    - binary_sensor.kitchen_cooking_area_ms
    - binary_sensor.kitchen_fridge_ms
- platform: group
  name: living_room_motion
  device_class: motion
  entities:
    - binary_sensor.living_room_dining_table_ms
    - binary_sensor.living_room_entrance_ms
    - binary_sensor.living_room_sofa_ms
- platform: group
  name: studio_motion
  device_class: motion
  entities:
    - binary_sensor.studio_ms_motion
    - binary_sensor.ms_studio_ep1_occupancy
- platform: group
  name: ensuite_motion
  device_class: motion
  entities:
    - binary_sensor.ensuite_ms
    - binary_sensor.ensuite_ceiling_ms_motion
- platform: group
  name: bedroom_motion
  device_class: motion
  entities:
    - binary_sensor.bedroom_ms_occupancy
    - binary_sensor.bedroom_instant_ms
- platform: group
  name: office_motion
  device_class: motion
  entities:
    - binary_sensor.office_ms_occupancy
    - binary_sensor.office_instant_ms
- platform: group
  name: hallway_motion
  device_class: motion
  entities:
    - binary_sensor.hallway_ms_motion
    - binary_sensor.ms_hallway_ep1_occupancy