---
- platform: group
  name: drums_vibration
  device_class: vibration
  all: true
  entities:
    - binary_sensor.vs_drums_bd_vibration
    - binary_sensor.vs_drums_xh_vibration
- platform: group
  name: kitchen_motion
  device_class: motion
  entities:
    - binary_sensor.kitchen_cooking_area_ms
    - binary_sensor.kitchen_fridge_ms
- platform: group
  name: living_room_motion
  device_class: motion
  entities:
    - binary_sensor.living_room_dining_table_ms
    - binary_sensor.living_room_entrance_ms
    - binary_sensor.living_room_sofa_ms
- platform: group
  name: studio_motion
  device_class: motion
  entities:
    - binary_sensor.ms_studio_ep1_occupancy
- platform: group
  name: ensuite_motion
  device_class: motion
  entities:
    - binary_sensor.ensuite_ms
    - binary_sensor.ensuite_ceiling_ms_motion
- platform: group
  name: bedroom_motion
  device_class: motion
  entities:
#    - binary_sensor.bedroom_ms_occupancy
#    - binary_sensor.bedroom_instant_ms
    - binary_sensor.bedroom_ms_epl_zone_bed_occupancy
- platform: group
  name: wardrobe_motion
  device_class: motion
  entities:
    - binary_sensor.wardrobe_ms_motion
    - binary_sensor.bedroom_ms_epl_zone_wardrobe_occupancy
- platform: group
  name: office_motion
  device_class: motion
  entities:
    - binary_sensor.office_ms_occupancy
    - binary_sensor.office_instant_ms
    - binary_sensor.drums_vibration
    - binary_sensor.desk_chair_ps
- platform: group
  name: hallway_motion
  device_class: motion
  entities:
    - binary_sensor.ms_hallway_ep1_occupancy
- platform: group
  name: bathroom_motion
  device_class: motion
  entities:
    - binary_sensor.bathroom_ms_motion