---
- platform: group
  name: kitchen_motion
  device_class: motion
  entities:
    - binary_sensor.kitchen_ms_occupancy
- platform: group
  name: living_room_motion
  device_class: motion
  entities:
    - binary_sensor.living_room_ms_occupancy
- platform: group
  name: studio_motion
  device_class: motion
  entities:
    - binary_sensor.studio_ms_occupancy
- platform: group
  name: ensuite_motion
  device_class: motion
  entities:
    - binary_sensor.ensuite_ms
