LAST_COOKED = "input_datetime.last_cooked"
LAST_CLEANED_KITCHEN = "input_datetime.last_cleaned_kitchen"
LAST_CLEANED_VACUUM_MOP = "input_datetime.last_cleaned_vacuum_mop"
KITCHEN_ACTIVITY = "input_select.kitchen_activity"
LIVING_ROOM_ACTIVITY = "input_select.living_room_activity"
