- id: '1664740449250'
  alias: Last cooked
  description: Updates the last cooked helper
  trigger:
  - type: motion
    platform: device
    device_id: 8f46192997475e37454b03ebbffc6aee
    entity_id: binary_sensor.kitchen_ms_motion
    domain: binary_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      timestamp: '{{ now().timestamp() }}'
    target:
      entity_id: input_datetime.last_cooked
  mode: single
